#!/bin/bash

function get {
    if [ ! -f "$1" ]; then
        echo "Downloading $1"
        curl "$2" > "$1"
    fi
}  

# Download libraries
mkdir -p _libs

get _libs/jquery.js http://code.jquery.com/jquery-2.2.1.min.js
get _libs/jquery.timeago.js http://timeago.yarp.com/jquery.timeago.js
get _libs/bootstrap.min.js https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
get _libs/bootstrap.min.css https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
get _libs/font-awesome-4.7.0.zip http://fontawesome.io/assets/font-awesome-4.7.0.zip

if [ ! -d "_libs/font-awesome-4.7.0" ]; then
    unzip -d _libs _libs/font-awesome-4.7.0.zip
fi

# Fonts
rsync -r _libs/font-awesome-4.7.0/fonts/* _static/fonts/

# CSS
cat _static/css/src/import.scss _libs/bootstrap.min.css _libs/font-awesome-4.7.0/css/font-awesome.min.css _static/css/src/style.scss \
    | sass --stdin --scss \
    | yui-compressor --type css \
    > _static/css/main.css

# JS
srcfiles=(_libs/jquery.js _libs/bootstrap.min.js _libs/jquery.timeago.js _libs/Chart.bundle.min.js _static/js/src/main.coffee _static/js/src/voting.coffee _static/js/src/updates.coffee)
for i in ${!srcfiles[*]}
do
    tmpfiles[$i]=$(mktemp)
    if [[ ${srcfiles[$i]} == *coffee ]]
    then
        coffee -b -c -p ${srcfiles[$i]} > ${tmpfiles[$i]}
    else
        cat ${srcfiles[$i]} > ${tmpfiles[$i]}
    fi
done
cat ${tmpfiles[*]} | yui-compressor --type js > _static/js/main.js
rm ${tmpfiles[*]}
